# Generated by Django 3.2.8 on 2021-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='little_description',
            field=models.CharField(default=11, max_length=600),
            preserve_default=False,
        ),
    ]
