# Generated by Django 3.2.8 on 2021-11-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_little_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
